<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jv_media_connector"
 *
 * Auto generated by Extension Builder 2019-06-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Media Connector',
    'description' => 'handle Media',
    'category' => 'plugin',
    'author' => 'Jörg Velletti',
    'author_email' => 'typo3@velletti.de',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
            'media_upload' => '1.0.2',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
